/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminasgit;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Diegomendez1997
 */
public class VentanaGanador extends javax.swing.JFrame {
    private int tiempo;
    private ArrayList<Usuario> partidas;
    private int n, m;
    static String nombreFichero;
    String separadorGlobal = System.getProperty("file.separator");
       String directorioGlobal = System.getProperty("user.home");
    /**
     * Creates new form VentanaGanador
     */
    public VentanaGanador(int tiempo, int n, int m) {
        initComponents();
        this.tiempo = tiempo;
        this.setLocationRelativeTo(null);
        this.tiempoLabel.setText(String.valueOf(tiempo));
        this.n = n;
        this.m = m;
        this.partidas = new ArrayList<Usuario>();
        
    }
    public boolean hacerBackUpMejoresTiempos() {
        try{
             if ((this.n == 10) && (this.m == 10)){
                nombreFichero = this.directorioGlobal+this.separadorGlobal+"mejoresTiemposPrincipiante";
            } else if((this.n == 16) && (this.m == 16)){
                nombreFichero = this.directorioGlobal+this.separadorGlobal+"mejoresTiemposIntermedio";
            } else if((this.n == 32) && (this.m == 16)){
               nombreFichero = this.directorioGlobal+this.separadorGlobal+"mejoresTiemposExperto";
            }
        FileOutputStream fos = new FileOutputStream(nombreFichero);
        BufferedOutputStream bos = new BufferedOutputStream(fos);
        ObjectOutputStream oos = new ObjectOutputStream(bos);
        for(int i = 0; i < partidas.size(); i++){
            oos.writeObject(partidas.get(i));
        }
            oos.flush();
            oos.close();
            return true;
        } catch (IOException ex) {
            System.err.println("ERROR: No ha sido posible hacer el backup del fichero  '" + nombreFichero + "'");
        }
        return false;
    }
    
    public boolean restaurarBackUpMejoresTiempos() {
        try {
            // Apertura
            
            //String rutaGlobal = System.getProperty("file.separator");
            
             if ((this.n == 10) && (this.m == 10)){
                nombreFichero = this.directorioGlobal+this.separadorGlobal+"mejoresTiemposPrincipiante";
            } else if((this.n == 16) && (this.m == 16)){
                nombreFichero = this.directorioGlobal+this.separadorGlobal+"mejoresTiemposIntermedio";
            } else if((this.n == 32) && (this.m == 16)){
               nombreFichero = this.directorioGlobal+this.separadorGlobal+"mejoresTiemposExperto";
            }
            
            FileInputStream fis = new FileInputStream(nombreFichero);
            BufferedInputStream bis = new BufferedInputStream(fis);
            ObjectInputStream ois = new ObjectInputStream(bis);
            
            // Lectura
            
            Usuario u = (Usuario) ois.readObject();
            if(u != null){
                while(u != null){
                    partidas.add(u);
                    u = (Usuario) ois.readObject();
                } 
            }
            
            //this.setVisible(false);
            // Cierre
            
            ois.close();
            return true;
        } catch (EOFException ex) {
            //System.err.println("ERROR: No ha sido posible recuperar el backup del fichero '" + nombreFichero + "'. Fin de fichero inesperado");
            
        } catch (ClassNotFoundException | IOException ex) {
            System.err.println("ERROR: No ha sido posible recuperar el backup del fichero '" + nombreFichero + "' " + ex.getMessage());
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreField = new javax.swing.JTextField();
        nombreUsuarioLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tiempoLabel = new javax.swing.JLabel();
        guardarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Congratulations you won!!!");

        nombreUsuarioLabel.setText("Nombre: ");

        jLabel1.setText("Tiempo: ");

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("¿Desea guardar la partida?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreUsuarioLabel)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(guardarButton)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombreField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(tiempoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cancelarButton))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreUsuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tiempoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton)
                    .addComponent(cancelarButton))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        Usuario usuario = new Usuario(nombreField.getText(), tiempo);
        //System.out.println(usuario);
        this.restaurarBackUpMejoresTiempos();
        if (partidas.size() < 10){
                partidas.add(usuario);
        } else {
            int peorTiempo = 0;
            int posicion = -1;
            for(int i = 0; i < partidas.size(); i++){
                if(partidas.get(i).getTiempo() > peorTiempo){
                    peorTiempo = partidas.get(i).getTiempo();
                    posicion = i;
                }
            }
            if(peorTiempo > usuario.getTiempo()){
                partidas.remove(posicion);
                partidas.add(usuario);
            } else {
                JOptionPane.showMessageDialog(this, "Tu tiempo no es de los diez mejores", "Guardar Partida", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }
        }
        this.hacerBackUpMejoresTiempos();
        
        this.setVisible(false);
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.setVisible(false);    }//GEN-LAST:event_cancelarButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreUsuarioLabel;
    private javax.swing.JLabel tiempoLabel;
    // End of variables declaration//GEN-END:variables
}
