/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminasgit;


import javax.swing.DefaultListModel;

import java.util.ArrayList;


/**
 *
 * @author Diegomendez1997
 */
public class VistaPartidas extends javax.swing.JFrame {
    
    private DefaultListModel<Usuario> modeloUsuarios;
    private DefaultListModel<Usuario> modeloUsuariosIntermedio;
    private DefaultListModel<Usuario> modeloUsuariosExperto;
    /**
     * Creates new form VistaGerente
     * 
     * @param partidasPrincipiante
     * @param partidasIntermedio
     * @param partidasExperto
     */
    public VistaPartidas(ArrayList<Usuario> partidasPrincipiante, ArrayList<Usuario> partidasIntermedio, ArrayList<Usuario> partidasExperto) {
        initComponents();
        this.modeloUsuarios = new DefaultListModel<>();
        this.usuariosPrincipiantesList.setModel(this.modeloUsuarios);
        this.modeloUsuariosIntermedio = new DefaultListModel<>();
        this.usuariosIntermediosList.setModel(this.modeloUsuariosIntermedio);
        this.modeloUsuariosExperto = new DefaultListModel<>();
        this.usuariosExpertosList.setModel(modeloUsuariosExperto);
        
        for (Usuario usuario: partidasPrincipiante) {
            this.modeloUsuarios.addElement(usuario);
        }
       
        
        for (Usuario usuario: partidasIntermedio) {
            this.modeloUsuariosIntermedio.addElement(usuario);
        }
        
        for (Usuario usuario: partidasExperto) {
            this.modeloUsuariosExperto.addElement(usuario);
        }
        
        
        
        /*
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        */
        
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                setVisible(false);
            }
        });
        
        
    }
    
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivelesTabbedPane = new javax.swing.JTabbedPane();
        principiantePanel = new javax.swing.JPanel();
        principianteScrollPane = new javax.swing.JScrollPane();
        usuariosPrincipiantesList = new javax.swing.JList<>();
        intermedioPanel = new javax.swing.JPanel();
        intermedioScrollPane = new javax.swing.JScrollPane();
        usuariosIntermediosList = new javax.swing.JList<>();
        expertoPanel = new javax.swing.JPanel();
        principianteScrollPane1 = new javax.swing.JScrollPane();
        usuariosExpertosList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mejores Tiempos");

        usuariosPrincipiantesList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        principianteScrollPane.setViewportView(usuariosPrincipiantesList);

        javax.swing.GroupLayout principiantePanelLayout = new javax.swing.GroupLayout(principiantePanel);
        principiantePanel.setLayout(principiantePanelLayout);
        principiantePanelLayout.setHorizontalGroup(
            principiantePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principiantePanelLayout.createSequentialGroup()
                .addComponent(principianteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        principiantePanelLayout.setVerticalGroup(
            principiantePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principianteScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        nivelesTabbedPane.addTab("Principiante", principiantePanel);

        usuariosIntermediosList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        intermedioScrollPane.setViewportView(usuariosIntermediosList);

        javax.swing.GroupLayout intermedioPanelLayout = new javax.swing.GroupLayout(intermedioPanel);
        intermedioPanel.setLayout(intermedioPanelLayout);
        intermedioPanelLayout.setHorizontalGroup(
            intermedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intermedioPanelLayout.createSequentialGroup()
                .addComponent(intermedioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        intermedioPanelLayout.setVerticalGroup(
            intermedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intermedioScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        nivelesTabbedPane.addTab("Intermedio", intermedioPanel);

        usuariosExpertosList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        principianteScrollPane1.setViewportView(usuariosExpertosList);

        javax.swing.GroupLayout expertoPanelLayout = new javax.swing.GroupLayout(expertoPanel);
        expertoPanel.setLayout(expertoPanelLayout);
        expertoPanelLayout.setHorizontalGroup(
            expertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expertoPanelLayout.createSequentialGroup()
                .addComponent(principianteScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        expertoPanelLayout.setVerticalGroup(
            expertoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principianteScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        nivelesTabbedPane.addTab("Experto", expertoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nivelesTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nivelesTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel expertoPanel;
    private javax.swing.JPanel intermedioPanel;
    private javax.swing.JScrollPane intermedioScrollPane;
    private javax.swing.JTabbedPane nivelesTabbedPane;
    private javax.swing.JPanel principiantePanel;
    private javax.swing.JScrollPane principianteScrollPane;
    private javax.swing.JScrollPane principianteScrollPane1;
    private javax.swing.JList<Usuario> usuariosExpertosList;
    private javax.swing.JList<Usuario> usuariosIntermediosList;
    private javax.swing.JList<Usuario> usuariosPrincipiantesList;
    // End of variables declaration//GEN-END:variables
}
