/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminasgit;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Diegomendez1997
 */
public class VistaNivelPersonalizado extends javax.swing.JDialog {
    private static BuscaminasGit buscaminas;
    
    /**
     * Creates new form AltaTrabajador
     * @param parent
     * @param modal
     * @param trabajador
     * @param modeloTrabajadores
     */
    public VistaNivelPersonalizado() {
        
        initComponents();
       
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroFilasLabel = new javax.swing.JLabel();
        numeroFilasSpinner = new javax.swing.JSpinner();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        numeroColumnasSpinner = new javax.swing.JSpinner();
        numeroColumnasLabel = new javax.swing.JLabel();
        numeroMinasLabel = new javax.swing.JLabel();
        numeroMinasSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Trabajador");

        numeroFilasLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        numeroFilasLabel.setText("Número de filas");

        numeroFilasSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        numeroColumnasSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        numeroColumnasLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        numeroColumnasLabel.setText("Número de columnas");

        numeroMinasLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        numeroMinasLabel.setText("Número de minas");

        numeroMinasSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(numeroFilasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroFilasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(numeroColumnasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroColumnasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aceptarButton)
                            .addComponent(numeroMinasLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numeroMinasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarButton))))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroFilasLabel)
                    .addComponent(numeroFilasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroColumnasLabel)
                    .addComponent(numeroColumnasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroMinasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroMinasLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton)
                    .addComponent(cancelarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        int opcionSeleccionada = JOptionPane.showConfirmDialog(this, "¿Quieres cancelar la edición de esta partida?", "Cancelar Edición Partida", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcionSeleccionada == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed

        int n = (int) this.numeroFilasSpinner.getValue();
        int m = (int) this.numeroColumnasSpinner.getValue();
        int nomines = (int) this.numeroMinasSpinner.getValue();
        buscaminas = new BuscaminasGit(n,m,nomines);
        this.setVisible(false);
       
    }//GEN-LAST:event_aceptarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel numeroColumnasLabel;
    private javax.swing.JSpinner numeroColumnasSpinner;
    private javax.swing.JLabel numeroFilasLabel;
    private javax.swing.JSpinner numeroFilasSpinner;
    private javax.swing.JLabel numeroMinasLabel;
    private javax.swing.JSpinner numeroMinasSpinner;
    // End of variables declaration//GEN-END:variables
}
